### ISSUE TITLE
formatter: handle projections correctly

### ISSUE THREAD

**Issue by gcampax** [Stanford-Mobisocial-IoT-Lab/thingtalk#10]
This is a hack idea:
If a parameter is projected out, ignore all messages that use that parameter.

Eg, given spotify:
[ "The danceability of this song is ${danceability:%}.", "This song is in ${key} ${modifier}" ]
if you project on danceability you get the first message only.
If you project on key and modifier, you get the second only.

**Comment by rayslxu** [comment]
Also, better handling of missing value is needed.
E.g., 
For missing `Date`, the default will print "Invalid Date", it should be something like "N/A"
