### ISSUE TITLE
ReferenceError: genRandomRemoteRules is not defined

### ISSUE THREAD

**Issue by carmilso** [Stanford-Mobisocial-IoT-Lab/ThingTalk#6]
Hi!
The variable genRandomRemoteRules is not defined in the file [index.js](https://github.com/Stanford-Mobisocial-IoT-Lab/ThingTalk/blob/master/index.js#L23)

**Comment by gcampax** [comment]
Yeah sorry that was a botched clean up of a semi botched merge.
It should be fixed now.
